[browser]

# Whether to send usage statistics to Streamlit.
# Default: true
# The value below was set in C:\Users\username\.streamlit\config.toml
gatherUsageStats = false

# Internet address where users should point their browsers in order to
# connect to the app. Can be IP address or DNS name and path.
# This is used to:
# - Set the correct URL for CORS and XSRF protection purposes.
# - Show the URL on the terminal
# - Open the browser
# Default: "localhost"
serverAddress = "localhost"

[server]

# The port where the server will listen for browser connections.
# Default: 8401
port = 8401

# If false, will attempt to open a browser window on start.
# Default: false unless (1) we are on a Linux box where DISPLAY is unset, or
# (2) we are running in the Streamlit Atom plugin.
headless = true

[client]

# Controls whether uncaught app exceptions are displayed in the browser. By default, this is set to True and Streamlit displays app exceptions and associated tracebacks in the browser.
# If set to False, an exception will result in a generic message being shown in the browser, and exceptions and tracebacks will be printed to the console only.
# Default: true
showErrorDetails = false

# Change the visibility of items in the toolbar, options menu, and settings dialog (top right of the app).
# Allowed values:
# "auto" : Show the developer options if the app is accessed through localhost and hide them otherwise.
# "developer" : Show the developer options.
# "viewer" : Hide the developer options.
# "minimal" : Show only options set externally (e.g. through Streamlit Community Cloud) or through st.set_page_config. If there are no options left, hide the menu.
# Default: "auto"
toolbarMode = "auto"

[theme]

# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
base = "light"

# Primary accent color for interactive elements.
primaryColor = "#337477"

# Background color for the main content area.
backgroundColor = "#E3EAEC"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#FFFFFF"

# Color used for almost all text.
textColor = "#337477"
